version: '3.8'
services:
  eureka_service:
    image: hafedh21/discovery-service:latest
    container_name: discovery-service
    hostname: discovery-service
    ports:
      - "9000:9000"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:9000/eureka/
    networks:
      - eventsphere-net

  resource-management-service:
    build: ./resource-management
    image: wiem23/event-resource-management:latest
    ports:
      - "8087:8087"
    hostname: ressource-event-management
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ressource-event-management
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka_service:9000/eureka
      - SERVER_PORT=8087
    depends_on:
      - eureka_service
      - postgres
    networks:
      - eventsphere-net

  reclamation-management-service:
    build: ./reclamation-management
    image: hafedh21/event-reclamation-management:latest
    ports:
      - "8084:8084"
    hostname: reclamation-event-management
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/reclamation_management?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:9000/eureka/
    depends_on:
      - eureka_service
      - mysql
    networks:
      - eventsphere-net

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - eventsphere-net

  event-management-service:
    build: ./event-management
    image: trabelsinour154/event-management:latest
    ports:
      - "8085:8085"
    hostname: event-management-service
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/eventdb
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka_service:9000/eureka
      - SERVER_PORT=8085
    depends_on:
      - eureka_service
      - mongo
    networks:
      - eventsphere-net

  payment-management-service:
    build: ./payment-management
    image: riahiyassine/payment-management:latest
    ports:
      - "8088:8088"
    hostname: payment-management
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:9000/eureka/
    depends_on:
      - eureka_service
    networks:
      - eventsphere-net

  gateway-service:
    build: ./Gateway
    image: wiem23/gateway-service:latest
    ports:
      - "8082:8082"
    hostname: gateway-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:9000/eureka/
      - SERVER_PORT=8082
    depends_on:
      - eureka_service
    networks:
      - eventsphere-net

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ressource-event-management
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - eventsphere-net

  mysql:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_DATABASE=reclamation-event-management
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - eventsphere-net
  mysql-partnership:
    image: mysql
    container_name: mysql-partnership
    environment:
      - MYSQL_DATABASE=partnership-management
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"  
    volumes:
      - mysql-partnership-data:/var/lib/mysql
    networks:
      - eventsphere-net

  partnership-management:
      build: ./partnership-management
      image: soufienaessalah/partnership-management:latest
      ports:
        - "8083:8083"
      hostname: partnership-management
      environment:
        - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-partnership:3306/partnership-management
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=root
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:9000/eureka/
        - SERVER_PORT=8083
      depends_on:
        - eureka_service
        - mysql-partnership
      networks:
        - eventsphere-net
networks:
  eventsphere-net:
    driver: bridge

volumes:
  postgres-data:
  mysql-data:
  mongo-data:
  mysql-partnership-data: